name: NPM Test & Webhook
on: push

jobs:
  webhook:
    name: NPM Test & Webhook action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run NPM Test & POST
      uses: SenorGrande/test-webhook@v1
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} 
